sudo: required

language: bash

services:
  - docker

install:
  - docker build -t quay.io/azavea/postgis:${TRAVIS_COMMIT:0:7} .

script:
  - docker run -d -p 5432:5432 quay.io/azavea/postgis:${TRAVIS_COMMIT:0:7}
  - sleep 5
  - psql -U postgres -h localhost -c "CREATE EXTENSION postgis;"

after_success:
  - docker login -e . -p "${QUAY_PASSWORD}" -u "${QUAY_USER}" quay.io
  - if [ "${TRAVIS_BRANCH}" == "develop" ]; then
    docker push quay.io/azavea/postgis:${TRAVIS_COMMIT:0:7};
    docker tag quay.io/azavea/postgis:${TRAVIS_COMMIT:0:7} quay.io/azavea/postgis:latest;
    docker push quay.io/azavea/postgis:latest;
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
    docker tag quay.io/azavea/postgis:${TRAVIS_COMMIT:0:7} quay.io/azavea/postgis:${TRAVIS_TAG};
    docker push quay.io/azavea/postgis:${TRAVIS_TAG};
    fi
