language: bash
services: docker

env:
  - POSTGIS_MAJOR=2.3 POSTGIS_VERSION=2.3.3+dfsg-1.pgdg90+1 PG_MAJOR=9.5 VARIANT=slim
  - POSTGIS_MAJOR=2.3 POSTGIS_VERSION=2.3.3+dfsg-1.pgdg90+1 PG_MAJOR=9.6 VARIANT=slim
  - POSTGIS_MAJOR=2.4 POSTGIS_VERSION=2.4.4+dfsg-4.pgdg90+1 PG_MAJOR=10.6 VARIANT=slim
  - POSTGIS_MAJOR=2.4 POSTGIS_VERSION=2.4.4+dfsg-4.pgdg90+1 PG_MAJOR=10.9 VARIANT=slim
  - POSTGIS_MAJOR=2.5 POSTGIS_VERSION=2.5.2+dfsg-1~exp1.pgdg90+1 PG_MAJOR=11.4 VARIANT=slim

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-postgis
      branch: master
