FROM postgres:%%PG_MAJOR%%

MAINTAINER Azavea <systems@azavea.com>

ENV POSTGIS_MAJOR %%POSTGIS_MAJOR%%
ENV POSTGIS_VERSION %%POSTGIS_VERSION%%

RUN \
      apt-get update && apt-get install -y --no-install-recommends \
              postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
              postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts \
      && rm -rf /var/lib/apt/lists/*
