#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%POSTGIS_MAJOR%%/$POSTGIS_MAJOR/" \
            -e "s/%%POSTGIS_VERSION%%/$POSTGIS_VERSION/" \
            -e "s/%%PG_MAJOR%%/$PG_MAJOR/" \
            "Dockerfile-$VARIANT.template" > Dockerfile

        docker \
            build -t "quay.io/azavea/postgis:$POSTGIS_MAJOR-postgres$PG_MAJOR-$VARIANT" .

        scripts/test

        docker images
    fi
fi
