#!/bin/bash

set -e
set -u

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish container images built from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker \
            login -u "${QUAY_USER}" -p "${QUAY_PASSWORD}" quay.io;

        docker \
            push "quay.io/azavea/postgis:$POSTGIS_MAJOR-postgres$PG_MAJOR-$VARIANT";
    fi
fi
