#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Test container images built from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker \
            run -d --name postgres-test -e POSTGRES_HOST_AUTH_METHOD=trust "quay.io/azavea/postgis:$POSTGIS_MAJOR-postgres$PG_MAJOR-$VARIANT"

        sleep 5

        trap "docker rm -f postgres-test" EXIT

        docker exec postgres-test psql -U postgres -c "SELECT version();"
        docker exec postgres-test psql -U postgres -c "CREATE EXTENSION postgis;"
        docker exec postgres-test psql -U postgres -c "SELECT PostGIS_Full_Version();"
        (( $(docker exec postgres-test psql -U postgres --no-align --tuples-only -c "SELECT ST_X(ST_Point(0,0));") == 0 ))
    fi
fi
