name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_major: ["9.6", "10.9", "11.4", "12.2", "12.4"]
        variant: [slim]
        include:
          - pg_major: "9.6"
            postgis_major: "2.4"
            postgis_version: 2.4.4+dfsg-4.pgdg90+1
          - pg_major: "10.9"
            postgis_major: "2.4"
            postgis_version: 2.4.4+dfsg-4.pgdg90+1
          - pg_major: "11.4"
            postgis_major: "2.5"
            postgis_version: 2.5.4+dfsg-1.pgdg90+1
          - pg_major: "12.2"
            postgis_major: "3"
            postgis_version: 3.0.2+dfsg-2.pgdg100+1
          - pg_major: "12.4"
            postgis_major: "3"
            postgis_version: 3.0.2+dfsg-2.pgdg100+1
    env:
      DOCKER_BUILDKIT: 1
      PG_MAJOR: ${{ matrix.pg_major }}
      POSTGIS_MAJOR: ${{ matrix.postgis_major }}
      POSTGIS_VERSION: ${{ matrix.postgis_version }}
      VARIANT: ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v2

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          QUAY_USER: ${{ secrets.QUAY_IMAGES_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_IMAGES_PASSWORD }}
